---
- name: Install and configure Zabbix agent on RHEL & Debian family Linux distros
  hosts: all
  debugger: on_failed
  
  tasks:
    - name: Install on CentOS 8
      yum:
        name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-1.el8.noarch.rpm
        state: present
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

    - name: Install on CentOS 7
      yum:
        name: https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-release-6.0-1.el7.noarch.rpm
        state: present
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

    - name: Install on Debian family
      apt:
        deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-2+$(lsb_release -sc)_all.deb
      when: ansible_distribution == 'Ubuntu'

    - name: Install zabbix-agent package
      package:
        name: zabbix-agent
        state: present

    - name: Copy configuration file to remote host
      copy:
        src: /home/devops/share/config/zabbix/zabbix_agentd.conf
        dest: /etc/zabbix/
        owner: root
        group: root
        mode: '0644'
        
    - name: restart zabbix-agent
      command: systemctl restart zabbix-agent
    
    - name: enable zabbix-agent
      command: systemctl enable zabbix-agent
