---
- hosts: '{{ hostlist }}'
  gather_facts: False

  tasks:
  - name: Copy file to remote hosts
    copy:
      src: /home/devops/share/config/zabbix/lib/get-device-ip.sh
      dest: /usr/lib/zabbix/internalscripts/network/
      owner: root
      group: root
      mode: '755'
