---
- hosts: '{{ hostlist }}'
  gather_facts: False

  tasks:
  - name: Copy file to remote hosts
    copy:
      src: /home/devops/share/config/zabbix/lib/devices-ip-list.txt
      dest: /usr/lib/zabbix/internalscripts/network/
      owner: root
      group: root
      mode: '644'
