---
- hosts: '{{ hostlist }}'
  gather_facts: False

  tasks:
  - name: Copy file to remote hosts
    copy:
      src: '{{ source }}'
      dest:  '{{ destination }}'
      owner: '{{ username }}'
      group: '{{ groupname }}'
      mode: '{{ permissions }}'
