---
- name: Copy public key authentication to remote system
  hosts: '{{ hostlist }}'
  gather_facts: false
  
  
  tasks:
  
    - name: Check if host is reachable
      wait_for:
        timeout: 0
      register: connect_rs
      ignore_unreachable: yes
      when: connect_rs is unreachable
    
    - name: Try first login and change the password
      delegate_to: localhost
      expect:
        command: sshpass -p {{ ansible_first_login_password }} ssh {{ ansible_ssh_common_args }} {{ ansible_user }}@{{ inventory_hostname }}
        timeout: 10
        responses:
          "Current password:": "{{ ansible_first_login_password }}"
          "New password:": "{{ ansible_password }}"
          "Retype new password:": "{{ ansible_password }}"

    - name: Setup the public key authentication
      authorized_key:
        state: present
        user: "{{ ansible_user }}"
        key: "{{ public_key }}"

    - name: "Gather facts about host"
      setup:
