---
- hosts: '{{ hostlist }}'
  gather_facts: False

  tasks:
  - name: Copy file to remote hosts
    copy:
      src: /home/devops/share/config/zabbix/zabbix_agentd.conf
      dest:  /etc/zabbix/
      owner: root
      group: root
      mode: '644'
