---
- name: Run custom command on the shell
  hosts: '{{ hostlist }}'
  
  
  tasks:
  
    - name: Custom command
      shell: "chmod +x /usr/lib/zabbix/internalscripts/network/get-device-ip.sh"
      failed_when: false

    - name: Custom command 2
      shell: "chmod +x /usr/lib/zabbix/internalscripts/network/get-host-ip.sh"
      failed_when: false
