---
- name: Send custom message to users console
  hosts: '{{ hostlist }}'
  
  
  tasks:
  
    - name: Custom command
      shell: wall -n "\033[0;31m {{ message }} \033[0m"
      failed_when: false
