---
- name: Installing required packages
  hosts: all
  gather_facts: no
  remote_user: devops
  become: true

  tasks:
    - name: Update system
      apt: update_cache=yes
    - name: Install system dependencies
      apt:
        name: dnsutils,mc,htop,netcat,netmap,net-tools,subversion
        state: present
