---
- name: Copy public key to remote system
  hosts: '{{ hostlist }}'
  gather_facts: false
  
  
  tasks:
  
    - name: Delete old key file
      shell: rm -f /home/devops/.ssh/authorized_keys
      ignore_errors: yes

    - name: Copy public key file
      copy:
        src: /home/devops/.ssh/authorized_keys
        dest: /home/devops/.ssh/
        owner: devops
        group: devops
        mode: '0600'
