---
- name: Install and configure Zabbix agent for your platform
  hosts: all
  
  tasks:
  - name: Install oficial repository
    command: rpm -Uvh https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-1.el8.noarch.rpm

  - name: Install monitoring agent
    command: dnf -y install zabbix-agent
    
  - name: Copy configuration file to host
    copy:
      src: /home/devops/share/config/zabbix/zabbix_agentd.conf
      dest: /etc/zabbix/
      owner: root
      group: root
      mode: '0644'

  - name: restart zabbix-agent
    command: systemctl restart zabbix-agent
    
  - name: enable zabbix-agent
    command: systemctl enable zabbix-agent
