---
- name: Disable Security-Enhanced Linux
  hosts: '{{ hostlist }}'

  tasks:
    - name: Dynamically disable it before the reboot
      shell: "setenforce 0"
    failed_when: false

    - name: Permanently disable
      lineinfile:
        dest: /etc/selinux/config
        regexp: "^SELINUX="
        line: "SELINUX=disabled"
