---
- name: Remove old kernels on RHEL & Debian family Linux distros
  hosts: '{{ hostlist }}'

  tasks:
    - name: Try to install more than 2 kernel packages
      ansible.builtin.lineinfile:
        dest: /etc/dnf/dnf.conf
        regexp: '^(#)?installonly_limit=\w*$'
        line: 'installonly_limit=2'
        state: present
      when: ansible_os_family == "RedHat"
      
    - name: Install yum-utils package on RHEL family
      package:
        name: yum-utils
        state: present
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

---
- name: Remove old kernels
  hosts: '{{ hostlist }}'
    shell: "rpm -q kernel | grep -v `uname -r` | grep -v `/sbin/grubby --default-kernel | sed -r 's#^/boot/vmlinuz-##'` | xargs rpm -e || true"

НАДО ДОРАБАТЫВАТЬ
