---
- hosts: all

  tasks:
  - name: Deny root from logging in
    ansible.builtin.lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^(#)?PermitRootLogin \w*$'
      line: 'PermitRootLogin yes'
      state: present
