---
- hosts: '{{ hostlist }}'
  gather_facts: False

  tasks:
  - name: Make sure chronyd is installed
    dnf:
     name: chrony
     state: latest
     update_cache: yes

  - name: Deploy configuration file
    template:
     src: /etc/chrony.conf
     dest: /etc/
     owner: root
     group: root
     mode: 0644
     backup: no
   notify: Restart chrony now
      
  - name: Ensure chrony services is started and enabled at boot
    service:
      name: chronyd
      state: restarted
      enabled: yes
