---
- hosts: '{{ hostlist }}'
  gather_facts: False

  tasks:
  - name: Make sure chronyd is installed
    dnf:
     name: chrony
     state: latest
     update_cache: yes

  - name: Deploy configuration file
    template:
     src: /etc/chrony.conf
     dest: /etc/
     owner: root
     group: root
     mode: 0644
     backup: no
      
  - name: Restart service chronyd
    service:
      name: chronyd
      state: restarted
      
  - name: Enable service and not touch the running state
    service:
      name: chronyd
      enabled: yes
