---
- name: Upgrade and Reboot RHEL & Debian family Linux distros
  hosts: all
  
  vars:
    reboot_connect_timeout: 5
    reboot_pre_reboot_delay: 0
    reboot_post_reboot_delay: 15
    reboot_timeout: 300
    
  tasks:
    # Upgrade RHEL family OS packages
    - name: Upgrade RHEL Family OS packages
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    # Debian Family upgrade
    - name: Update repositories cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
      when: ansible_os_family == "Debian"
    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist
      when: ansible_os_family == "Debian"

    # Reboot host after upgrade
    - name: Check if a reboot is needed on all upgrade servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: "{{ reboot_connect_timeout }}"
        reboot_timeout: "{{ reboot_timeout }}"
        pre_reboot_delay: "{{ reboot_pre_reboot_delay }}"
        post_reboot_delay: "{{ reboot_post_reboot_delay }}"
        test_command: uptime
      when: reboot_required_file.stat.exists
