---
- name: Create user with admin access on RHEL & Debian family Linux distros
  hosts: '{{ hostlist }}'
  vars:
    password: '{{ nohash }}'
  
  tasks:
  
    - name: Check if the user exist
      shell: "grep -q '{{ username }}' /etc/passwd"
      ignore_errors: yes
      register: checkout
      
    - name: Send message in console if the user exist
      debug:
        msg: User '{{ username }}' already exists and next action stopped!
      when: checkout.rc == 0
      
    - name: Stop tne play if the user exist
      meta: end_play
      when: checkout.rc == 0
  
    - name: Create a new login user on RHEL family
      user:
        name: '{{ username }}'
        password: "{{ password | password_hash('sha512') }}"
        groups:
          - wheel
        state: present
      when: ansible_os_family == "RedHat"

    - name: Create a new login user on Debian family
      user:
        name: '{{ username }}'
        password: "{{ password | password_hash('sha512') }}"
        groups:
          - sudo
        state: present
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      
    - name: Create a new sudoers file for user
      file:
        path: /etc/sudoers.d/{{ username }}
        state: touch
        mode: 0400
        owner: root

    - name: Add sudoers content in file
      copy:
        dest: /etc/sudoers.d/{{ username }}
        content: |
          {{ username }} ALL=(ALL) NOPASSWD: ALL

    - name: Expiry time for the user in epoch  
      user:
        name: '{{ username }}'
        expires: '{{ date }}'
      when: date is defined

    - mail:
        host: localhost
        port: 25
        to: John Smith <akuznetsov@5-55.ru>
        subject: Ansible-report
        body: 'System {{ ansible_hostname }} has been successfully provisioned.'
