---
- name: Create user with admin access
  hosts: '{{ hostlist }}'
  
  tasks:
  
    - name: Expiry time for the user in epoch  
      user:
        name: '{{ username }}'
        expires: '{{ timestamp }}'
      when: date is defined
