---
- name: Delete user and home directory
  hosts: '{{ hostlist }}'
 
  
  tasks:
  
    - name: Delete user to group and home directory
      user:
        name: '{{ username }}'
        state: absent
        remove: yes 
        force: yes
        
    - name: Delete a sudoers file for user
      shell: rm -f /etc/sudoers.d/{{ username }}
